use_frameworks!

target 'TKCocoaModule_Example' do
  pod 'TKCocoaModule', :path => '../'

  target 'TKCocoaModule_Tests' do
    inherit! :search_paths

    
    
    post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['SWIFT_VERSION'] = '4.2'
         end
     end
    end
    
    
    
  end
end
